server:
  port: 9000
spring:
  application:
    name: cards # same name with configserver resources
  datasource:
    url: jdbc:postgresql://localhost:5434/cardsdb
    username: 'postgres'
    password: 'root'
  ## TODO: enable this after development
  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: "prod" # ["", "qa", "prod"]
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: "localhost"
    port: 5672 # or 15672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" # enable and expose all management endpoint supported by the spring boot actuator
  endpoint:
    shutdown:
      enabled: true # shutdown the cards ms
  info:
    env:
      enabled: true # enabled env related information

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true # cards ms will try to fetch the registry details whenever it's trying to connect with other microservices.
    registerWithEureka: true # cards ms will be registered with the Eureka server.
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "Cards"
    description: "Cards Application"
    version: "1.0.0"