services:
  accounts:
    image: "cisu2/account:001"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m # max 700mb memory
    networks:
      - cisu2network
  loans:
    image: "cisu2/loans:001"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cisu2network # tag all ms under the same network
  cards:
    image: "cisu2/cards:001"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cisu2network

# create a network with the name of "cisu2network" and drive of "bridge"
networks:
  cisu2network:
    driver: "bridge"
