server:
  port: 8090
spring:
  application:
    name: loans # same name with configserver resources
  datasource:
    url: jdbc:postgresql://localhost:5433/loansdb
    username: 'postgres'
    password: 'root'
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: "default" # ["" || "default", "qa", "prod"]
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: "localhost"
    port: 5672 # or 15672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" # enable and expose all management endpoint supported by the spring boot actuator