server:
  port: 8090
spring:
  application:
    name: loans # same name with configserver resources
  datasource:
    url: jdbc:postgresql://localhost:5433/loansdb
    username: 'postgres'
    password: 'root'
  ## TODO: enable this after development
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: "default" # ["" || "default", "qa", "prod"]
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: "localhost"
    port: 5672 # or 15672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" # enable and expose all management endpoint supported by the spring boot actuator
  endpoint:
    shutdown:
      enabled: true # shutdown the loans ms
  info:
    env:
      enabled: true # enabled env related information


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true # loans ms will try to fetch the registry details whenever it's trying to connect with other microservices.
    registerWithEureka: true # loans ms will be registered with the Eureka server.
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "Loans"
    description: "Loans Application"
    version: "1.0.0"