services:
  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672" # core activities of the Rabbitmq (AMQP protocol for apps)
      - "15672:15672" # management of the Rabbitmq (Web UI interface)
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml # file name
      service: network-deploy-service # service to import from the file

  # Accounts database
  accountsdb:
    image: postgres:18.3-alpine3.23
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "accountsdb"
    extends:
      file: common-config.yml # file name
      service: microservice-db-config # service to import from the file contain also network-deploy-service

  # Loans Database
  loansdb:
    container_name: loansdb
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: "loansdb"
    extends:
      file: common-config.yml # file name
      service: microservice-db-config # service to import from the file

  # Cards Database
  cardsdb:
    container_name: cardsdb
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: "cardsdb"
    extends:
      file: common-config.yml # file name
      service: microservice-db-config # service to import from the file

  configserver:
    image: "cisu2/configserver:003"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8071/actuator/health/readiness || exit 1"
      interval: 10s # 3. run test command every  10 sec
      timeout: 5s # 4. fail the test if takes more than 5 sec
      retries: 10 # 2. if there is a failure try again for 10 times
      start_period: 5s # 1. start the test after 5 sec
    extends:
      file: common-config.yml # file name
      service: microservice-base-config # service to import from the file


  accounts:
    image: "cisu2/account:003"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy # service_completed_successfully
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://accountsdb:5432/accountsdb"

    extends:
      file: common-config.yml # file name
      service: microservice-configserver-config # service to import from the file

  loans:
    image: "cisu2/loans:003"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy # service_completed_successfully
      loansdb:
        condition: service_healthy
    environment:
      #      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      #      SPRING_PROFILES_ACTIVE: "default"
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://loansdb:5432/loansdb"
    extends:
      file: common-config.yml # file name
      service: microservice-configserver-config # service to import from the file

  cards:
    image: "cisu2/cards:003"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy # service_completed_successfully
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://cardsdb:5432/cardsdb"
    extends:
      file: common-config.yml # file name
      service: microservice-configserver-config # service to import from the file

# create a network with the name of "cisu2network" and drive of "bridge"
networks:
  cisu2network:
    driver: "bridge"
