build:
  version: "1.0"

accounts:
  message: "Welcome to Breaking Bank accounts related prod APIs "
  contactDetails:
    name: "John Doe - Product Owner"
    email: "john@doe-po.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384