build:
  version: "2.0"

cards:
  message: "Welcome to breaking Bank cards related QA APIs "
  contactDetails:
    name: "John Doe - QA Lead"
    email: "john@doe-qa.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267