build:
  version: "1.0"

loans:
  message: "Welcome to  Breaking Bank loans related prod APIs "
  contactDetails:
    name: "John Doe - Product Owner"
    email: "john@doe-po.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956