build:
  version: "3.0"

loans:
  message: "Welcome to Breaking Bank loans related local APIs "
  contactDetails:
    name: "Anna Montana - Developer"
    email: "anna@montana.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934