build:
  version: "2.0"

loans:
  message: "Welcome to Breaking Bank loans related QA APIs "
  contactDetails:
    name: "John Doe - QA Lead"
    email: "john@doe.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467