server:
  port: 8080

spring:
  application:
    name: accounts # same name with configserver resources
  datasource:
      url: jdbc:postgresql://localhost:5432/accountsdb
      username: 'postgres'
      password: 'root'
  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # create the tables automatically
    show-sql: true # show the sql queries


  profiles:
    active: "prod" # ["", "qa", "prod"]
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: "localhost"
    port: 5672 # or 15672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" # enable and expose all management endpoint supported by the spring boot actuator
