server:
  port: 8071

encrypt:
  key: "YopJrhs6d9Wx7iQopoQr"

spring:
  application:
    name: configserver
  profiles:
    active: git
#
  #    active: native   # διαβάζει τοπικά αρχεία (Native Profile)
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/giorgos-grekis/java-microservices-architecture-k8s-helm-config.git"
          default-label: "main"
          timeout: 5 # wait for 5 seconds
          clone-on-start: true
          force-pull: true # overwrite all local changes
        #        native:
          # search-locations: "classpath:/config"
          # Reading configurations from a file system location
#          search-locations: "file:///home/***/**/configserver/src/main/resources/config/"

  # Git Repository
#  cloud:
#    config:
#      server:
#        git:
#          uri: "https://github.com/{username}/repo-configs.git"